loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 10Gi

promtail:
  enabled: true
  volumeMounts:
  - name: nginx
    mountPath: /var/log/nginx
    readOnly: true
  volumes:
  - name: nginx
    hostPath:
      path: /var/log/nginx
  scrapeConfigs:
  - job_name: nginx-ingress
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx-ingress
        __path__: /var/log/nginx/*.log
    # pipeline_stages:
    # - match:
    #     selector: '{job="nginx-ingress"}'
    #     stages:
    #     - regex:
    #         expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
    #     - labels:
    #         remote_addr:
    #         #remote_user:
    #         #time_local:
    #         method:
    #         request:
    #         #protocol:
    #         status:
    #         body_bytes_sent:
    #         #http_referer:
    #         #http_user_agent:

fluent-bit:
  enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.5.0
  persistence:
    enabled: true
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 1Gi

prometheus:
  enabled: false

filebeat:
  enabled: false

logstash:
  enabled: false
