{{- if .Values.rbac.create -}}
{{- $fullName := include "alica.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName | quote }}
  labels:
    app: "{{ template "alica.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Values.rbac.serviceAccountName "" }}
    name: {{ $fullName | quote }}
    {{- else }}
    name: {{ .Values.rbac.serviceAccountName | quote }}
    {{- end }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ $fullName | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
