{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cerebro.serviceAccountName" . }}
  labels:
    app: {{ template "cerebro.name" . }}
    chart: {{ template "cerebro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
