apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9913"
  name: nginx-server
  namespace: ops
spec:
  selector:
    app: nginx-server
  ports:
  - port: 80
    targetPort: 80
  - port: 84
    targetPort: 84
  - port: 443
    targetPort: 443