apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  namespace: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/aoisola/elastalert:alpine-3.13
        imagePullPolicy: IfNotPresent
        name: elastalert
        command:
          - "/bin/start"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2560Mi
        volumeMounts:
        - name: elastalert-conf
          subPath: config.yaml
          mountPath: "/opt/conf/config.yaml"
        - name: elastalert-rules
          subPath: rule.yaml
          mountPath: "/opt/rules/rule.yaml"
        - name: elastalert-rules
          subPath: rule2.yaml
          mountPath: "/opt/rules/rule2.yaml"
      volumes:
      - name: elastalert-conf
        configMap:
          name: elastalert-conf
      - name: elastalert-rules
        configMap:
          name: elastalert-rules