# Default values for log-pilot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.cn-hangzhou.aliyuncs.com/acs/log-pilot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.9.7-filebeat"
  #tag: "0.9.7-fluentd"

env:
  - name: LOGGING_OUTPUT
    value: kafka
  - name: KAFKA_BROKERS
    value: kafka-headless:9092

volumes:
- hostPath:
    path: /var/run/docker.sock
    type: ""
  name: docker
- hostPath:
    path: /etc/localtime
    type: ""
  name: localtime
- hostPath:
    path: /
    type: ""
  name: root
- hostPath:
    path: /var/lib/filebeat
    type: DirectoryOrCreate
  name: filebeat-lib
- hostPath:
    path: /var/log/filebeat
    type: DirectoryOrCreate
  name: filebeat-log

volumeMounts:
- mountPath: /var/run/docker.sock
  name: docker
  readOnly: true
- mountPath: /etc/localtime
  name: localtime
  readOnly: true
- mountPath: /host
  name: root
  readOnly: true
- mountPath: /var/lib/filebeat
  name: filebeat-lib
- mountPath: /var/log/filebeat
  name: filebeat-log

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
    - SYS_ADMIN

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
